plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
}

def kitVersion = providers.gradleProperty('kitVersion').orElse('1.0.0').get()

dependencies {
    testImplementation "com.xq:jvm-test-kit:${kitVersion}"
    testImplementation platform('org.junit:junit-bom:6.0.0')
    testImplementation 'org.junit.jupiter:junit-jupiter:6.0.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}
